web:
  container_name: ghost_env
  image: trunk/ghost_env

  command: "/bin/bash -l -c 'npm start --porduction'"

  ports:
    - "2368:2368"


  working_dir: /ghost
  volumes:
    - ./:/ghost

  restart: always
